name: clean_architechture # The name of the App
settings:
  base:
    CODE_SIGN_STYLE: Manual
configs:
  Dev Debug: debug
  Staging Debug: debug
  Production Debug: debug
  Dev Release: release
  Staging Release: release
  Production Release: release
configFiles:
  Dev Debug: clean_architechture/Utils/Config/xcconfigs/dev.xcconfig
  Staging Debug: clean_architechture/Utils/Config/xcconfigs/staging.xcconfig
  Production Debug: clean_architechture/Utils/Config/xcconfigs/production.xcconfig
  Dev Release: clean_architechture/Utils/Config/xcconfigs/dev.xcconfig
  Staging Release: clean_architechture/Utils/Config/xcconfigs/staging.xcconfig
  Production Release: clean_architechture/Utils/Config/xcconfigs/production.xcconfig
options: # Some general settings for the project
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 4 # indent by 4 spaces
  tabWidth: 4 # a tab is 4 spaces
  postGenCommand: pod install
    
targets: # The List of our targets
  clean_architechture:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    devices: [iPhone]
    sources:
      #Sources
      - path: clean_architechture
    scheme:
      testTargets:
        - clean_architechtureTests
      gatherCoverageData: true
      configVariants:
        - Dev
        - Staging
        - Production
    settings:
      base:
       TARGETED_DEVICE_FAMILY: 1
       OTHER_SWIFT_FLAGS: $(inherited) $(SWIFT_FLAGS)
       INFOPLIST_FILE: clean_architechture/Info.plist
      configs:
        Dev Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            PROVISIONING_PROFILE_SPECIFIER: Development Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Dev Release:
            CODE_SIGN_IDENTITY: iPhone Distribution
            PROVISIONING_PROFILE_SPECIFIER: Distribution Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Staging Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            PROVISIONING_PROFILE_SPECIFIER: Development Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Staging Release:
            CODE_SIGN_IDENTITY: iPhone Distribution
            PROVISIONING_PROFILE_SPECIFIER: Distribution Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Production Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            PROVISIONING_PROFILE_SPECIFIER: Development Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Production Release:
            CODE_SIGN_IDENTITY: iPhone Distribution
            PROVISIONING_PROFILE_SPECIFIER: Distribution Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
    preBuildScripts:
      - name: R.swift
        basedOnDependencyAnalysis: false
        script: |
                "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/clean_architechture/Utils/Resources/R.generated.swift"
      - name: Swiftlint
        script: |
                "${PODS_ROOT}/SwiftLint/swiftlint"
      - name: SwiftFormat
        script: |
                "${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" "$SRCROOT"

  clean_architechtureTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: clean_architechtureTests
    dependencies:
      - target: clean_architechture
